version: '1.0'
name: pipeline-20251220
displayName: 发布到NuGet
triggers:
  trigger: auto
  push:
    tags:
      include:
        - ^v\d+\.\d+\.\d+(-[\w.]+)?$
stages:
  - name: stage-1549ccd4
    displayName: 打包并发布
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: 打包并发布到NuGet
        certificate: ''
        image: mcr.m.daocloud.io/dotnet/sdk:9.0
        command:
          - 'echo "=== 调试信息 ===" && pwd && ls -la && find / -name "*.sln" 2>/dev/null | head -5 && find / -name "Apq.ChangeBubbling.csproj" 2>/dev/null'
        notify: []
        strategy:
          retry: '0'
