version: '1.0'
name: pipeline-20251220
displayName: 发布到NuGet
triggers:
  trigger: auto
  push:
    tags:
      include:
        - ^v\d+\.\d+\.\d+(-[\w.]+)?$
variables:
  global:
    - NUGET_API_KEY
stages:
  - name: stage-1549ccd4
    displayName: 打包并发布
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: 打包并发布到NuGet
        certificate: ''
        image: mcr.m.daocloud.io/dotnet/sdk:9.0
        command:
          - 'echo "NUGET_API_KEY: ${NUGET_API_KEY}" && dotnet restore && dotnet pack Apq.ChangeBubbling/Apq.ChangeBubbling.csproj -c Release -o ./nupkgs && for pkg in ./nupkgs/*.nupkg; do dotnet nuget push "$pkg" -s https://api.nuget.org/v3/index.json -k ${NUGET_API_KEY} --skip-duplicate; done'
        notify: []
        strategy:
          retry: '0'
