version: '1.0'
name: pipeline-20251220
displayName: 发布到NuGet
triggers:
  trigger: auto
  push:
    tags:
      include:
        - ^v\d+\.\d+\.\d+(-[\w.]+)?$
stages:
  - name: stage-1549ccd4
    displayName: 打包并发布
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@dotnet
        name: pack_nuget_6
        displayName: 打包.net6.0
        dotnetVersion: '6.0'
        commands:
          - '# input your command here'
          - dotnet restore
          - dotnet publish -c Release -o out
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./out
        caches:
          - ~/.nuget/packages
        notify: []
        strategy:
          retry: '0'
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        notify: []
        strategy:
          retry: '0'
        dependsOn: pack_nuget_6
