version: '1.0'
name: pipeline-20251220
displayName: 发布到NuGet
triggers:
  trigger: auto
  push:
    tags:
      include:
        - ^v\d+\.\d+\.\d+(-[\w.]+)?$
stages:
  - name: stage-1549ccd4
    displayName: 打包并发布
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: 基于镜像的脚本执行
        certificate: ''
        image: registry.cn-chengdu.aliyuncs.com/apq/publish-to-nuget
        command:
          - '# 请在此输入您想执行的脚本'
          - echo 'Hello Gitee!'
        notify: []
        strategy:
          retry: '0'
